---
# Playbook to install and set-up nihongoparserd

- name: Check if nihongoparserd is already present
  shell: which nihongoparserd
  register: install_state
  ignore_errors: yes
- name: Installation skip message
  debug: msg="nihongoparserd already installed and force_install == false; skipping installation"
  when: install_state is success and force_install == false
- name: Force install message
  debug: msg="nihongoparserd already installed; reinstalling it (force_intall == true)"
  when: install_state is success and force_install == true

- include: install_nihongoparserd.yml
  when: install_state is failed or force_install == true
