---
# Tasks to fetch latest tatoeba-php code and optionally update cakephp configs

- name: Fetch the code from github repository
  become: false
  git:
    repo: "{{ git_rep }}"
    dest: "{{ code_dir }}"
    version: "{{ repo_version }}"
    remote: "{{ git_remote }}"

- name: Copy CakePHP config files from remote host
  become: false
  fetch:
    src: "{{ code_dir }}/config/{{ item }}.template"
    dest: "roles/update_code/templates/{{ item }}.template"
    flat: yes
  with_items:
  - app_local.php

- name: Template out CakePHP config files
  become: false
  template:
    src: "{{ item }}.template"
    dest: "{{ code_dir }}/config/{{ item }}"
  with_items:
  - app_local.php

- name: Fetch composer dependencies
  become: false
  composer:
    command: install
    global_command: no
    working_dir: "{{ code_dir }}"

- name: Allow www-data to write avatars
  file:
    path: "{{ code_dir }}/{{ item }}"
    state: directory
    mode: 0775
    group: www-data
  with_items:
  - webroot/img/profiles_128
  - webroot/img/profiles_36

- name: Allow www-data to write cache and logs
  file:
    path: "{{ code_dir }}/{{ item }}"
    state: directory
    mode: 0775
    group: www-data
    recurse: yes
  with_items:
  - logs
  - tmp

- name: Install gettext
  apt:
    name: gettext
