---
- hosts: all
  become: true

  tasks:
    - name: Dump all databases
      mysql_db:
        state: dump
        name: all
        target: /tmp/dump.sql

    - name: Compress databases
      archive:
        path: /tmp/dump.sql
        remove: yes

    - name: Copy backup file to host
      fetch:
        src: /tmp/dump.sql.gz
        dest: "{{mysqldump_backup_file}}"
        flat: yes

    - name: Remove backup file from guest
      file:
        path: /tmp/dump.sql.gz
        state: absent

    - name: Print backup details
      debug:
        msg: Databases backuped into {{mysqldump_backup_file}}. Will be restored upon new machine creation.
