---

- name: Delete old database with same name if it exists
  shell: echo "DROP DATABASE IF EXISTS {{mysql_db_name}}" | mysql -u {{mysql_user}} -p{{mysql_password}}

- name: Create a new mysql database
  shell: echo "CREATE DATABASE {{mysql_db_name}}" | mysql -u {{mysql_user}} -p{{mysql_password}}

- name: Initialize database schema
  shell: find {{code_dir}}/docs/database/tables -type f -exec cat {} \; | mysql -u {{mysql_user}} -p{{mysql_password}} {{mysql_db_name}}

- name: Fill database with initial values
  shell: mysql -u {{mysql_user}} -p{{mysql_password}} {{mysql_db_name}} < {{code_dir}}/docs/database/{{item}}
  with_items:
  - import/users.sql
  - import/groups.sql
  - import/sinograms.sql
  - import/sinogram_subglyphs.sql

- name: Fill languages table
  shell: "{{code_dir}}/bin/cake init_languages_table"

- name: Set up ACLs
  shell: chdir={{code_dir}} sh docs/database/acl/{{item}}
  become: true
  become_user: www-data
  with_items:
  - acos
  - aros
  - aros_acos

- name: Install database triggers
# This task requires mysql root for creating triggers
  shell: cat {{code_dir}}/docs/database/triggers/*.sql | mysql -u root -p{{mysql_root_password}} {{mysql_db_name}}
