---

- name: Bail if not Debian-like
  fail:
    msg: Please adapt this role for your distribution
  when: "ansible_os_family != 'Debian'"

- name: Install Sphinx package
  apt:
    name: sphinxsearch
    state: present
  when: "ansible_distribution_release == 'stretch'"

- name: Download Sphinx package
  get_url:
    url: "{{sphinx_deb_url}}"
    dest: /tmp/sphinx.deb
  when: "ansible_distribution_release == 'wheezy'"

- name: Remove Sphinx source package
  file:
    path: /tmp/sphinx.deb
    state: absent

- name: Create sphinsearch group
  group:
    name: sphinxsearch
    state: present
    system: yes

- name: Create sphinsearch user
  user:
    name: sphinxsearch
    state: present
    group: sphinxsearch
    comment: "Sphinx fulltext search service"
    system: yes

- name: Install additional systemd.unit file
  copy:
    src: sphinxsearch.service
    dest: /etc/systemd/system/sphinxsearch.service
    owner: root
    group: root
    mode: 0644
  notify: Reload daemons unit files
  when: "ansible_distribution_release == 'stretch'"

- name: Remove init.d file
  file:
    path: /etc/init.d/sphinxsearch
    state: absent
  when: "ansible_distribution_release == 'stretch'"

- name: Start and Enable sphinxsearch
  service:
    name: sphinxsearch
    state: started
    enabled: yes
    daemon_reload: yes
  when: "ansible_distribution_release == 'stretch'"

- name: Set the location of pid file in Sphinx's init.d script
  command: sed -i 's|^PIDFILE=.*|PIDFILE="sphinx_pid_file}}|' /etc/init.d/sphinxsearch
  when: "ansible_distribution_release == 'wheezy'"
- name: Set the location of log directory in Sphinx's init.d script
  command: sed -i 's|^LOGDIR=.*|LOGDIR="sphinx_log_dir}}|' /etc/init.d/sphinxsearch
  when: "ansible_distribution_release == 'wheezy'"
- name: Make Sphinx to be run by the sphinxsearch user
  command: sed -i '/start-stop-daemon .*--stop/ s/start-stop-daemon/start-stop-daemon --chuid sphinxsearch/;/start-stop-daemon .*--start/ s/start-stop-daemon/start-stop-daemon --user sphinxsearch/' /etc/init.d/sphinxsearch
  when: "ansible_distribution_release == 'wheezy'"
- name: Allow Sphinx to open more than 1024 files
  command: sed -i '/start-stop-daemon .*--start/i ulimit -n 2048' /etc/init.d/sphinxsearch
  when: "ansible_distribution_release == 'wheezy'"
