---
# Tasks to backup the database, configs and other important directories

- fail: msg="Variable 'version' not set; please give the version to restore to through '-e version=n' where n is the version number"
  when: version is not defined
- name: Check if the revision number is valid
  script: check_version.sh {{code_dir}} {{version|int}}
- name: Change the current link
  script: change_version.sh {{code_dir}} {{version|int}}
  register: result
- debug: msg="{{result.stdout}}"
  when: result is success
